### ISSUE TITLE
vCloud Director with Grafana

### ISSUE THREAD

**Issue by vidipmishra** [mycloudrevolution/Grafana-Telegraf-vCloud-PsCore#1]
I am new to this and I have issue while running this script the output is below .Please help me in fixing this.

Invoke-RestMethod :
At /Grafana-Telegraf-vCloud-PsCore/vCloud.ps1:16 char:10
+ $Login = Invoke-RestMethod -uri $Uri -Method Post -Headers $Headers - ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: POST, R...rShell/6.1.1
}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Invoke-RestMethod :
At /Grafana-Telegraf-vCloud-PsCore/vCloud.ps1:26 char:17
+ ... ]$orgVdcs = Invoke-RestMethod -uri $Uri -Method Get -Headers $Headers ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: GET, Re...rShell/6.1.1
}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Invoke-RestMethod :
At /Grafana-Telegraf-vCloud-PsCore/vCloud.ps1:32 char:15
+ ... ML]$vApps = Invoke-RestMethod -uri $Uri -Method Get -Headers $Headers ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: GET, Re...rShell/6.1.1
}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Invoke-RestMethod :
At /Grafana-Telegraf-vCloud-PsCore/vCloud.ps1:38 char:13
+ [XML]$VMs = Invoke-RestMethod -uri $Uri -Method Get -Headers $Headers
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: GET, Re...rShell/6.1.1
}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Invoke-RestMethod :
At /Grafana-Telegraf-vCloud-PsCore/vCloud.ps1:44 char:21
+ ... gNetworks = Invoke-RestMethod -uri $Uri -Method Get -Headers $Headers ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: GET, Re...rShell/6.1.1
}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Invoke-RestMethod :
At /Grafana-Telegraf-vCloud-PsCore/vCloud.ps1:50 char:22
+ ... eGateways = Invoke-RestMethod -uri $Uri -Method Get -Headers $Headers ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: GET, Re...rShell/6.1.1
}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
vCloudStats orgVdcCountTotal=0
vCloudStats vAppCountTotal=0
vCloudStats VMCountTotal=0
vCloudStats VMCountPoweredOff=0
vCloudStats orgNetworkCountTotal=0
vCloudStats edgeGatewaysTotal=0
Invoke-RestMethod :
At /Grafana-Telegraf-vCloud-PsCore/vCloud.ps1:103 char:11
+ $Logout = Invoke-RestMethod -uri $Uri -Method Delete -Headers $Header ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: DELETE,...rShell/6.1.1
}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
PS /Grafana-Telegraf-vCloud-PsCore>

**Comment by vidipmishra** [comment]
Please someone help.

**Comment by vMarkusK** [comment]
Hello @vidipmishra ,

might you please let us know a few details regarding your environment:
- PSCore Version?
- OS?
- vCD Version?

I have verified the script today against vCD 8.20 and it still works fine. But anyways, I have added an additional error handling during the Login Call. 
Might you please test with the updated version and let us know the result?

Best regards,
Markus

**Comment by vidipmishra** [comment]
![error400](https://user-images.githubusercontent.com/46746326/51455809-41905a00-1d71-11e9-9095-0877f05b9def.JPG)
Hi,

Thanks a lot for the reply.

Now I am getting error : "StatusCode :400 "
Please find the details you asked for.

PSCore Version? - 6.1.1
OS?Ubuntu - 16.04
vCD Version?- 9.1.08825784

**Comment by vMarkusK** [comment]
Hi,

might you please try in your WebBrowser or via wget (on you ubuntu box):
https://<API FQDN>/api/versions

I have verified the Script with exact your Environment without trouble. 
Have you ever used the API of your vCD Instance?

**Comment by vidipmishra** [comment]
![wget](https://user-images.githubusercontent.com/46746326/51465303-a9ed3480-1d8d-11e9-87a8-5258ef40be6d.JPG)

Hi,

This is the output of wget which looks working.
no I have never used API of the vCD Instance .

**Comment by vMarkusK** [comment]
Hi,

are you able to create a **temporary** account for me (in your Org) to verify the problem?

I need:
- Instance FQDN
- Organization Name
- **temporary** Username / Password (Org Admin)

You can chose the way of communication you prefer:
https://mycloudrevolution.com/en/contact/

**Comment by vidipmishra** [comment]
Hi,
Can you please check your inbox and let me know your preference.

Thanks.

**Comment by vidipmishra** [comment]
Hi Markus,
Now API issue is fix but i am still unable to get data , it shows the output as below.'
Please help,

![error](https://user-images.githubusercontent.com/46746326/51936120-c3ceed00-2407-11e9-96c3-583387c0295b.JPG)

**Comment by vMarkusK** [comment]
Does your user have "organization administrator" permissions?
And just to make sure, the Organization has some of these objects?

**Comment by vidipmishra** [comment]
Hi Markus,

Yes , both the things are in place.

Regards
Vivek

On Jan 29, 2019 10:20 PM, Markus Kraus <notifications@github.com> wrote:

Does your user have "organization administrator" permissions?
And just to make sure, the Organization has some of these objects?

**Comment by vMarkusK** [comment]
Hi,
it's very difficult to help you with that problem.
I have verified the Script with exact same Versions of the environment. It Works. I can only imagine that the User Permission is not right or something similar.

I have sent you a few screenshots of how to use Postman. Reproducing the Script-Steps in Postman might help you...

**Comment by vidipmishra** [comment]
Hi Markus,

What role / access does the user need to work this , also could you please share the screen shots again , i cannot find it.

Regards
Vivek

Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by vMarkusK** [comment]
A wrong user was used (System instead of Organization Administrator).

**Comment by vidipmishra** [comment]
Hi Markus,

Now I have org administrator role , do I need to give only user name or is there any specific format to give user name ( may be user@Organization).

Thanks
Vivek



On Feb 6, 2019 10:20 PM, Markus Kraus <notifications@github.com> wrote:

A wrong user was used (System instead of Organization Administrator).

**Comment by vMarkusK** [comment]
That's the right format.

Am Do., 7. Feb. 2019, 10:15 hat vidipmishra <notifications@github.com>
geschrieben:

> Hi Markus,
>
> Now I have org administrator role , do I need to give only user name or is
> there any specific format to give user name ( may be user@Organization).
>
> Thanks
> Vivek
>
>
>
